version: '3'

services:
  api:
    build: .
    command: python run.py
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
