version: '3.8'
services:
  web-account:
    build:
      context: .
      target: account-api
    environment:
      DB_HOST: db-account
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET_KEY: asddkjsd1k3j2193wksdjkas021
    command: python run.py
    volumes:
      - .:/app
    ports:
      - 5111:5000
    depends_on:
      - db-account
    restart: on-failure
  web-market-courier:
    build:
      context: .
      target: marketplace-courier
    environment:
      DB_HOST: db-marketplace
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET_KEY: asddkjsd1k3j2193wksdjkas021
    command: python run.py
    volumes:
      - .:/app
    ports:
      - 5222:5000
    depends_on:
      - db-marketplace
    restart: on-failure
  web-market-owner:
    build:
      context: .
      target: marketplace-owner
    environment:
      DB_HOST: db-marketplace
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET_KEY: asddkjsd1k3j2193wksdjkas021
    command: python run.py
    volumes:
      - .:/app
    ports:
      - 5333:5000
    depends_on:
      - db-marketplace
    restart: on-failure
  web-market-customer:
    build:
      context: .
      target: marketplace-customer
    environment:
      DB_HOST: db-marketplace
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      JWT_SECRET_KEY: asddkjsd1k3j2193wksdjkas021
    command: python run.py
    volumes:
      - .:/app
    ports:
      - 5444:5000
    depends_on:
      - db-marketplace
    restart: on-failure
  db-account:
    image: postgres
    restart: always
    ports:
      - '5436:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  db-marketplace:
    image: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres