version: '3.8'
services:
  db-account:
    image: postgres
    restart: always
    ports:
      - '5436:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  db-marketplace:
    image: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres